
services:
  stefano:
    build: 
      context: .
      target: hugo-develop
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "1313:1313"
    volumes:
      - ./website:/home/app/website
